model: rdkit
# datapath: project_folder/embeddings/rdkit/combo_sciplex_prep_hvg_filtered_rdkit2D_embedding.parquet 29
datapath: /mnt/linjienas2/lzq/chemCPA/embeddings/rdkit/combo_sciplex_prep_hvg_filtered_rdkit2D_embedding.parquet
