# datapath: project_folder/embeddings/rdkit/lincs_full_smiles_rdkit2D_embedding.parquet
datapath: /mnt/linjienas2/lzq/CyclePerturbNet/train/scripts/embeddings/rdkit/lincs_full_smiles_rdkit2D_embedding_chemberta.parquet
model: rdkit